web:
  container_name: ntm_web
  image: silintl/php7
  ports:
    - "80:80"
  volumes:
    - ./src:/var/www
    - ./conf/apache:/etc/apache2/sites-enabled/
  links:
    - db
db:
  container_name: ntm_db
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./db/:/var/lib/mysql/
  environment:
    MYSQL_DATABASE: ntm
    MYSQL_USER: ntm_user
    MYSQL_PASSWORD: ntm_password
    MYSQL_ROOT_PASSWORD: ntm_password
