front:
  image: nginx-fpm
  ports:
    - "80:80"
  links:
    - db
  volumes:
    - ./src:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor
db:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./db/:/var/lib/mysql/
  environment:
    MYSQL_ROOT_PASSWORD: root
