version: '2'

services:
  web:
    container_name: ptm_web
    build: .
    ports:
      - 80:80
#      - "9000:9000"
    volumes:
      - ../:/var/www/html/
      - ./conf/apache:/etc/apache2/sites-enabled/
      - ./conf/php:/usr/local/etc/php/
  db:
    container_name: ptm_db
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/:/var/lib/mysql/
      - ./conf/mysql:/etc/mysql/
    environment:
      MYSQL_DATABASE: ptm
      MYSQL_USER: ptm_user
      MYSQL_PASSWORD: ptm_password
      MYSQL_ROOT_PASSWORD: ptm_password
